### ISSUE TITLE
Glossary

### ISSUE THREAD

**Issue by henrikalbrecht** [henrikalbrecht/I05-Virtuelle-Maschinen#1]
Working on the Glossar will be a permanent task during the whole project, therefore it will be present in every Iteration.

Iteration-2: Eric and Julius start with the Glossar, this way they can catch up on vocabulary they might be missing. Furthermore everybody gets a base knowledge about what technologies we are using and what kind of software our productowner wants.

**Comment by don-ny** [comment]
@stony02 , @Julius0123456789 
Glossar
—> If you need help with asciidoc, please check OPAL module for SE I
—> If you struggle with terms for the glossary, here are a few ideas for you to get warmed-up:
- VM
- VM pool
- VM cluster
- template
- IP
- DNS
- SQL
- PostgreSQL
- Django
- … (all the other technologies we use, like docker etc.)
