### ISSUE TITLE
Create risk list

### ISSUE THREAD

**Issue by don-ny** [henrikalbrecht/I05-Virtuelle-Maschinen#12]
files to be produced:
- docs/project_management/risk_list.adoc

further information:
- OPAL
- template on discord

Remark:
- create the file if it's not part of the HTW templates

**Comment by arshactually2** [comment]
Started assessing risks of different types, like Technical, Human Factors, etc. Working on developing a list.

**Comment by don-ny** [comment]
- @arshactually2 you can upload the first version of the list
- create a new folder *resources* in docs/project_managemet/ and put the risk list there
- in the file risk_list.adoc please link to the newly uploaded file

**Comment by arshactually2** [comment]
Completed the formatting
