### ISSUE TITLE
Rework usecase 2

### ISSUE THREAD

**Issue by henrikalbrecht** [henrikalbrecht/I05-Virtuelle-Maschinen#123]
Our usecases are packed with loads of functionalities to destinguish between them wen need to specifically focus on each of those individually. 

we got "Anlegen", "Bearbeiten" and "Löschen"

One has to be the basic flow and the other ones are alternative flows. Before the basic flow can start usecase 1 has to be done beforehand.

The "wesentliche Szenarios" need to be merged to be one "szenario" and wen need to cut out the fourth bulletpoint.

use the pdf form the discord for further information

**Comment by don-ny** [comment]
Done:
updated wireframes in PR #129

ToDo:
documentation UC02

**Comment by don-ny** [comment]
done
