### ISSUE TITLE
Frontend extensions

### ISSUE THREAD

**Issue by henrikalbrecht** [henrikalbrecht/I05-Virtuelle-Maschinen#148]
- Fix VM allocation color schema
- Add correct color for allocation status
- Add Email Template Page (Talk with Jakub)

**Comment by arshactually2** [comment]
- Fixed VM allocation color schema.
- Added correct colors for allocation status and is function. 
- Created the frontend of VM Templates refering to new wireframes.
- Created the frontend of Email Templates refering to new wireframes.
- HTW Dresden Logo is clickable and reloads the page. 
- The neue VM button open and closes the VM allocation pop up. 
- Added Border to the Neue VM button. 
- The issue with allocating 'windows' is fixed. 
- Removed the buttons Backup and Restore.

**Comment by arshactually2** [comment]
Pushed the changes to the frontend_remastered branch, ran into some errors with backend, got to know there were some issues with backend and Jakub's new branch had'nt been merged. So I'd suggest to merge this frontend_remastered branch first.
