### ISSUE TITLE
Pull request needs a branch

### ISSUE THREAD

**Issue by henrikalbrecht** [henrikalbrecht/I05-Virtuelle-Maschinen#15]
As we´ve seen in #5 if we keep changing a branch that is currently in a pull request, every change an that specific branch will be included in the pull request, that is not a good workflow because we might overlook some changes on the review.

To address this everybody need to work with feature branches. The workflow will be explained in the teammeeting on the 27.11.2023.

**Comment by don-ny** [comment]
Workflow changes agreed:
- no more forks
- everybody commit their most recent work on the fork and initiate pull request for it
- after that, delete your fork (locally and from github)
- clone [main repo from Henrik](https://github.com/henrikalbrecht/I05-Virtuelle-Maschinen/) and use this from now on
- create branch reflecting you current work 
  - example: create branch "doc-vision" if you're working on the vision.adoc documentation
  - commit changes made to vision.adoc to the branch

@henrikalbrecht please edit / add the stuff I forgot (maybe step-by-step with git commands?)

I have understood the changes to the workflow (please ask us if something is unclear):
- [ ] AS
- [ ] ES
- [ ] HA
- [ ] PK
- [ ] JK
- [ ] CN
- [ ] JV

**Comment by don-ny** [comment]
@Julius0123456789 are you finished with this?

**Comment by don-ny** [comment]
closing, all have acknowledged the changes
