### ISSUE TITLE
Dev Workshop: React, Django and db work

### ISSUE THREAD

**Issue by don-ny** [henrikalbrecht/I05-Virtuelle-Maschinen#18]
To get experience with collaboration in GitHub/branches and improving knowledge about Django and React, @arshactually2 agreed to conduct a developer-focused workshop.

This issue is only for planning of the workshop and roughly outlines the workshop content.
When you're finished with the planning, please give me a heads-up. 
(You can also attach your plan as a file if you want.)

### Useful ressources:
[Django](https://docs.djangoproject.com/en/4.2/intro/tutorial01/)
[React](https://react.dev/learn)

### Guidelines:
- ~~no~~ minimal database work (due to time constraints) - please use [SQLite](https://docs.djangoproject.com/en/4.2/ref/databases/#sqlite-notes)
- keep the examples simple
- think about examples that could be useful for our project later on
- work with a new GitHub project and use branches
- make the workshop extensive enough so ~~5~~ 3 people (incl. yourself) can participate at the same time
- workshop should be able to be conducted from everywhere (remote participation)
- workshop can be tech-focused (**target audience is Devs + Testing** and optional Henrik and I)

@arshactually2 please mark the checkboxes when you have planned the according sections
### Technical content:
- [ ] Examples with Python+Django (for example: the polling tutorial linked above)
- [ ] Examples with React (you know better than me)
- [ ] Use one GitHub project and work with branches

**Comment by arshactually2** [comment]
Discussed the Aim, structure of the workshop, and the deadline with Team leader @don-ny on 01.12.23.

**Comment by arshactually2** [comment]
Commenced the communication between Devs and plan of action.

**Comment by don-ny** [comment]
@arshactually2 meeting with Mr. Z today resulted in the request to do this workshop as "VM-style" workshop.
meaning:
- Please don't do a "ToDo" app but simulate a list of VMs with information etc.
- try to arrange this workshop in a way that enables you to re-use certain parts for our main project
