### ISSUE TITLE
Setup work environment

### ISSUE THREAD

**Issue by henrikalbrecht** [henrikalbrecht/I05-Virtuelle-Maschinen#2]
We need a common ground to work on. Therefore everybody sets up his environment according to the git forking workflow mentioned in the first Iteration 2 team meeting. 

RECOMMENDATION:
VSCode
GitGraph(VSCode extension)

You are free to use any IDE or Codeeditor, but choosing extravagant software might cause less help from teammates beacuse they probably dont use that technology.

When you encounter any problems dont hesistate and just ask for help. 
It is a sign of strength to ask for help!

If you setup your complete work environment according to the mentioned workflow please comment on the task. When everybody commented the task is done!

**Comment by henrikalbrecht** [comment]
DONE

**Comment by clemens29** [comment]
DONE

**Comment by coderJakub** [comment]
DONE

**Comment by don-ny** [comment]
DONE

**Comment by arshactually2** [comment]
DONE

**Comment by Julius0123456789** [comment]
DONE
________________________________
Von: Henrik ***@***.***>
Gesendet: Montag, 20. November 2023 18:52:34
An: henrikalbrecht/I05-Virtuelle-Maschinen
Cc: Viertel, Julius; Assign
Betreff: [henrikalbrecht/I05-Virtuelle-Maschinen] Setup work environment (Issue #2)


We need a common ground to work on. Therefore everybody sets up his environment according to the git forking workflow mentioned in the first Iteration 2 team meeting.

RECOMMENDATION:
VSCode
GitGraph(VSCode extension)

You are free to use any IDE or Codeeditor, but choosing extravagant software might cause less help from teammates beacuse they probably dont use that technology.

When you encounter any problems dont hesistate and just ask for help.
It is a sign of strength to ask for help!

If you setup your complete work environment according to the mentioned workflow please comment on the task. When everybody commented the task is done!

**Comment by don-ny** [comment]
@stony02 what's the status?

**Comment by stony02** [comment]
Done
