### ISSUE TITLE
Architecture Notebook

### ISSUE THREAD

**Issue by henrikalbrecht** [henrikalbrecht/I05-Virtuelle-Maschinen#3]
The architecture is a vital part of the projects documentation. According to the OpenUP roles its the architects job to maintain it.

Iteration-2: Henrik is starting to dive into the architecture book and get a feeling of what is asked for

**Comment by henrikalbrecht** [comment]
ed792361662f4a8e449c4e7942c97d9cfbf60979

**Comment by don-ny** [comment]
PR #102
