### ISSUE TITLE
refine Use Case Model

### ISSUE THREAD

**Issue by henrikalbrecht** [henrikalbrecht/I05-Virtuelle-Maschinen#30]
In our PO meeting we got some new information regarding the Use Case Model that needs to be incorporated.

Update from meeting with PO:
refined list of use cases:

    UC01: VMs auflisten Auflisten der VMs
    UC02: VMs verwalten new
    UC03: Vergabe verwalten Vergabe der VMs
    UC04: Email Templates verwalten
    UC05: VM Templates verwalten
    UC06: Backup verwalten new
    UC07: VMs zurücksetzen Zurücksetzung der VMs
    delete: Login des Nutzers

Priorities (for producing the individual use cases):

    High: UC01, UC03
    Mid: UC02, UC04, UC05
    Low: UC06, UC07

**Comment by henrikalbrecht** [comment]
#38

**Comment by don-ny** [comment]
The diagram was updated but not the prior section in use-case_model.adoc

please update "2. Identifizierte Use Cases" in acordance with the diagram and add the priorities to them.
Convert the current text based format into a table with the format:

_Use Case | Name | Priorität
**UC01** | VMs auflisten | high
**UC02** | VMs verwalten | mid_
...


UC03: Vergabe verwalten
UC04: Email Templates verwalten
UC05: VM Templates verwalten
UC06: Backup verwalten
UC07: VMs zurücksetzen
