### ISSUE TITLE
wireframe use case 1

### ISSUE THREAD

**Issue by henrikalbrecht** [henrikalbrecht/I05-Virtuelle-Maschinen#33]
According to use case 1 we need a wire frame that we can incorporate into the detailed use case description.

**Comment by Julius0123456789** [comment]
Isn´t that something like a frontend sketch? I thougt somebody else created like a frontend sketch on Figma

**Comment by henrikalbrecht** [comment]
The wireframe is more like a super light weight sketch. The Figma mockup we made was way more enhanced. Take a look at the "Praktikum" there you can find an example of how it can look. 

If there are any concerns regarding the look of the wireframe ask a teammate you think is best suitable for that kind of exchange.

**Comment by Julius0123456789** [comment]
Ich habe in der Uni im PC-Labor mal ein Wireframe erzeugt, da mir dort Visual Paradigm in vollem Umfang zur Verfügung steht. Der Wireframe an sich war erstmal nur zu Übungszwecken für mich. Kann man Visual Paradigm auch kostenlos für daheim downloaden?

Ich habe mir die Datei per Mail zugeschickt, eine VPP-Datei, die ich bei mir jetzt nirgends anschauen kann. Kann man die auch als JPG oder ähnliches speichern?

Das andere Problem ist, das ich nicht hundertprozentig weiß, wie ich das Wireframe aufteilen soll. Gibt es irgendwo einen groben Aufbau für die Use-Cases (z.B. Figma) oder habe ich da selber Gestaltungsspielraum? 

Darüber können wir ja mal morgen im Meeting sprechen.
