### ISSUE TITLE
Prepare VM for project usage

### ISSUE THREAD

**Issue by don-ny** [henrikalbrecht/I05-Virtuelle-Maschinen#49]
We received login information for our VM we will use for development.
@coderJakub I forwarded you an email with the login credentials and some additional tasks to prepare the VM so you can start development.

**Comment by don-ny** [comment]
@coderJakub for now, please focus on:
- disabling ssh for root user (if not already included in the VM)
- check individual auto-update settings (if none available, leave it as is)

**Comment by coderJakub** [comment]
- changed the password
- added a backup user with sudo rights
- blocked root access
- installed the firewall ufw with an open port for ssh, http, https
- set up automatic updates
