### ISSUE TITLE
Prototype UI for functionality "VM Verwaltung"

### ISSUE THREAD

**Issue by don-ny** [henrikalbrecht/I05-Virtuelle-Maschinen#6]
**UserStory:**
As manager of VMs I want to be able to manage/administrate the pool of VMs efficiently.
The current administration of VMs is being done via text files, which is inconvenient, time consuming and leaves a lot of room for mistakes. To improve the workflow and reduce chances for mistakes, I want to be able to manage my VMs via a GUI.

**Requirements:**
- easy to access
- simple design
- not too colorful
- no animations

**Functionalities:**
- display pool of VMs with basic information (VM name, assigned team | unassigned)
- add a VM (ability to add one specific VM to the pool)
- remove VM (ability to remove one specific VM from the pool)
- modify VM (ability to edit properties of one specific VM)
- inspect VM (view all **properties** of one specific VM)
--> **properties** known so far:
- common name (iseproject01)
- IP (IPv4 address)
- DNS name (iseproject01.informatik.htw-dresden.de)
- network access (internal or external)
- contact information (name, email address)

**Info/Help:**
Good starting point could be [Figma](https://www.figma.com/), which is a design tool for UI prototyping.

**Additional info from product owner:**
Please use additional info from the email that was forwarded to you by @don-ny 
```
geschlossenes Netz
   • iseproject01: [IP], [DNS name](http://[DNS name])
   • iseproject02: [IP], [DNS name](http://[DNS name])
   • iseproject03:...
   • iseproject13:

offenes Netz
   • iseproject07e: 
...
```

**Comment by don-ny** [comment]
checked figma prototype - need quick talk with at least one of @arshactually2 @clemens29 @coderJakub

**Comment by arshactually2** [comment]
Initialized the Figma prototype, added basic inspiration webpages, and constructed the login page. Sent @clemens29 and @coderJakub Figma tutorials and discussed basic requirements. Then both of them worked on developing the prototype.  Dated : 22.11.23

**Comment by clemens29** [comment]
Added used & unused VM's menus with a window for the VM's properties with @coderJakub. Date: 23.11.2023
Then had a short talk about the prototype with @don-ny and @arshactually2.
