### ISSUE TITLE
Get to know PostgreSQL 

### ISSUE THREAD

**Issue by clemens29** [henrikalbrecht/I05-Virtuelle-Maschinen#62]
- Get familiar with implementation of PostgreSQL 
- usage of PostgreSQL in Python

resources:
https://www.youtube.com/watch?v=miEFm1CyjfM
https://www.youtube.com/watch?v=KqcS3P32s6Y

**Comment by don-ny** [comment]
@clemens29 @coderJakub wie ist der Stand hier?

**Comment by clemens29** [comment]
@don-ny Habe die PostgreSQL Datenbank bereits im Backend initialisiert, die läuft jetzt allerdings eben nur lokal auf meinem Rechner

**Comment by don-ny** [comment]
@clemens29 cool, bitte mal zusammen mit Jakub mit ner separaten Umgebung bisschen rumprobieren, wie man Daten mit der REST API vom backend in PostgreSQL schreibt

**Comment by don-ny** [comment]
**--- INFO ---**

Don't close this issue - we will use it when the new semester starts.
