### ISSUE TITLE
Create vision

### ISSUE THREAD

**Issue by don-ny** [henrikalbrecht/I05-Virtuelle-Maschinen#7]
We aim to present our first vision during the next meeting with the product owner.
The document [vision.adoc](https://github.com/henrikalbrecht/I05-Virtuelle-Maschinen/blob/main/docs/requirements/vision.adoc)

**Aim for this issue is to have the following sections of vision.adoc filled:**
**open sections:**

**finished sections:**
- Fachliche Motivation (@don-ny)
- Problem Statement (@don-ny)
- Positionierung des Produkts (@don-ny)
- Benutzerumgebung (@henrikalbrecht)
- Bedarfe und Hauptfunktionen (@henrikalbrecht)
- Zusammenfassung der Stakeholder (@clemens29)

**Guidelines for this issue:**
1. please choose freely a section you want to work on
2. comment the section you have chosen to prevent others from working on it
3. submit a pull request when you are finished with a section
4. add the finished section to the passage "finished sections" and remove it from "open sections"
5. start with step 1 as long as there are open sections

**Comment by clemens29** [comment]
Ich würde die Zusammenfassung der Stakeholder übernehmen.

**Comment by henrikalbrecht** [comment]
#9

**Comment by don-ny** [comment]
see Pull request #9

**Comment by don-ny** [comment]
PO meeting 27 NOV 2023:

ToDo:
- add Stakeholder "Projektgruppe"
- change Stakeholder "Auftraggeber/Admin" to "Christoph Zirkelbach" and mention him as "Auftraggeber" in description
- remove Stakeholder "Softwareentwicklungsteam"
- chapter "Positionierung"
- update priorities "Bedarfe und Hauptfunktionen" 
- add "Email Templates verwalten" as "Hauptfunktion"
- remove "Wenig Farben" und "keine Animationen" from "Zusätzliche Produkanforderungen"
