### ISSUE TITLE
modify model fields

### ISSUE THREAD

**Issue by coderJakub** [henrikalbrecht/I05-Virtuelle-Maschinen#75]
**Change name of fields**

- DNS name -> Hostname
- team_name -> project_name
- team_email -> contact_email
- created_at  -> awarded_on

**Remove fields**

- team_id
- external_net?

**Add fields**

- contact_name

**Change field config**

- operating_sys: dropdown (initially only Windows and Linux)
- awarded_on: default->null, Generate when allocationStage changed to "in_use"
- operating_sys, project_name, contact_email, contact_name: default->null, required->False

**Comment by coderJakub** [comment]
Hab ich etwas vergessen @don-ny

**Comment by don-ny** [comment]
everything you mentioned +
**Change name of fields**
add new option "Gesperrt" to allocationStage, so a VM can represent a blocked state due to administrative reasons (for example security incidents)
