### ISSUE TITLE
Finalize documentation ahead of submission

### ISSUE THREAD

**Issue by don-ny** [henrikalbrecht/I05-Virtuelle-Maschinen#78]
We need to finalize our documentation ahead of the submission to the professor.
This task needs to be done by everybody in order to split-up the work load.

**My idea for this is:**
- 21 JAN 24: Deadline for Arshnoor, Clemens, Henrik, Julius & Jakub
- 24 JAN 24: Deadline for Paul
- 25 JAN 24: Corrections done by Paul, proof read done by Henrik
- 26 JAN 24: Last-minute corrections and submission into OPAL

### Relevant documents to be done
See [OPAL, Belegarbeiten Organisatorisches, pages 11, 12](https://bildungsportal.sachsen.de/opal/auth/RepositoryEntry/21511831560/CourseNode/1636947272947851009/Belegarbeiten_WS2023-24_Organisatorisches.pdf)
These are the documents taken into account for this semester:
**Technical Specification**
- [x] Vision (Paul)
- [x] Use Case Model (Paul)
- [x] UC01 #59 (Clemens)
- [x] UC03 (Clemens)
- [x] Remaining Use Cases (Clemens)
- [x] Systemwide requirements (Paul, 4. zusätzliche Anforderungen, 4.1 (react wasnt mentioned by Mr. Z)
- [x] Glossary (Julius, see comments on #77 and #83 - all team: send useful words for the glossary to Julius)
- [x] Domain model (Henrik)

**Project and iteration planning**
- [x] Project plan (Paul)
- [x] Risk list (Arshnoor, Jakub, Paul - we can keep using #63 for this)
- [x] Iteration plans for 2 iterations of our choosing (Paul, target: 25 JAN)
- [ ] check documentation against input from last Coach meeting (Paul, target: 26 JAN)

**Design documentation**
- [x] Architecture notebook (Henrik)
- [x] Test cases (Clemens - please collab with Jakub & Arshnoor on this)
- [x] Data structure (Jakub, Clemens, Arshnoor - potential classes, database design etc.)
- [ ] (object design)

Also helpful for good documentation:
[OPAL, Häufige Fehler im Beleg](https://bildungsportal.sachsen.de/opal/auth/RepositoryEntry/21511831560/CourseNode/1641785315897232009)

**Comment by henrikalbrecht** [comment]
domain model and architecture notebook PRs are open.
